#!/bin/bash
set -x
export PATH=$PATH:$(go env GOPATH)/bin
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/common.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/candles.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/events.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/orders.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/portfolios.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/security.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/proto/tradeapi/v1/stops.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/grpc/tradeapi/v1/candles.prot
oprotoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/grpc/tradeapi/v1/events.proto
oprotoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/grpc/tradeapi/v1/orders.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/grpc/tradeapi/v1/portfolios.proto
protoc --proto_path=contracts/proto/tradeapi/v1 --go_out=/tradeapi --go_opt=paths=source_relative --go_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi --go-grpc_out=/tradeapi --go-grpc_opt=paths=source_relative --go-grpc_opt=Mcommon.proto=github.com/DenisKuzin/tradeapi contracts/grpc/tradeapi/v1/securities.proto
